"""Backward-compatible re-exports. Prefer `lib.runtime` and `lib.session`."""

from lib.runtime import (
    ACTIVATION_PHRASE,
    AGENTS,
    AGENTS_DIR,
    DASHBOARD_AVAILABLE,
    DNA_AVAILABLE,
    MODELS_AVAILABLE,
    NSFW_AVAILABLE,
    PRODUCTION_AVAILABLE,
    QUOTA_AVAILABLE,
    ROOT,
    ROLE_CARD_PREVIEW_CHARS,
    SEQ_AVAILABLE,
    STUDIO_VERSION,
    build_studio_dashboard,
    cached_plugin_details,
    core_agent_count,
    get_grok_client,
    list_role_card_options,
    read_role_card_preview,
    render_footer,
    run_cli,
)
from lib.session import (
    PRODUCTION_OPTIONS,
    SESSION_DEFAULTS,
    clip_story,
    complexity_for_estimate,
    init_session_defaults,
    select_index,
    session_quota_snapshot,
)

__all__ = [
    "ACTIVATION_PHRASE",
    "AGENTS",
    "AGENTS_DIR",
    "DASHBOARD_AVAILABLE",
    "DNA_AVAILABLE",
    "MODELS_AVAILABLE",
    "NSFW_AVAILABLE",
    "PRODUCTION_AVAILABLE",
    "PRODUCTION_OPTIONS",
    "QUOTA_AVAILABLE",
    "ROOT",
    "ROLE_CARD_PREVIEW_CHARS",
    "SEQ_AVAILABLE",
    "SESSION_DEFAULTS",
    "STUDIO_VERSION",
    "build_studio_dashboard",
    "cached_plugin_details",
    "clip_story",
    "complexity_for_estimate",
    "core_agent_count",
    "get_grok_client",
    "init_session_defaults",
    "list_role_card_options",
    "read_role_card_preview",
    "render_footer",
    "run_cli",
    "select_index",
    "session_quota_snapshot",
]