/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AspectRouteImport } from './routes/aspect'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as ColorRouteImport } from './routes/color'
import { Route as CompositionRouteImport } from './routes/composition'
import { Route as ConsistencyRouteImport } from './routes/consistency'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DopRouteImport } from './routes/dop'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GraduateRouteImport } from './routes/graduate'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LensesRouteImport } from './routes/lenses'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as PackRouteImport } from './routes/pack'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShotsRouteImport } from './routes/shots'
import { Route as SoundRouteImport } from './routes/sound'
import { Route as WorkflowsRouteImport } from './routes/workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AspectRoute = AspectRouteImport.update({
  id: '/aspect',
  path: '/aspect',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionRoute = CompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsistencyRoute = ConsistencyRouteImport.update({
  id: '/consistency',
  path: '/consistency',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DopRoute = DopRouteImport.update({
  id: '/dop',
  path: '/dop',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduateRoute = GraduateRouteImport.update({
  id: '/graduate',
  path: '/graduate',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LensesRoute = LensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsRoute = ShotsRouteImport.update({
  id: '/shots',
  path: '/shots',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundRoute = SoundRouteImport.update({
  id: '/sound',
  path: '/sound',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/aspect': typeof AspectRoute
  '/bible': typeof BibleRoute
  '/budget': typeof BudgetRoute
  '/cards': typeof CardsRoute
  '/color': typeof ColorRoute
  '/composition': typeof CompositionRoute
  '/consistency': typeof ConsistencyRoute
  '/craft': typeof CraftRoute
  '/dna': typeof DnaRoute
  '/docs': typeof DocsRoute
  '/dop': typeof DopRoute
  '/editing': typeof EditingRoute
  '/glossary': typeof GlossaryRoute
  '/graduate': typeof GraduateRoute
  '/lab': typeof LabRoute
  '/learn': typeof LearnRoute
  '/lenses': typeof LensesRoute
  '/lighting': typeof LightingRoute
  '/movement': typeof MovementRoute
  '/pack': typeof PackRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/quiz': typeof QuizRoute
  '/recap': typeof RecapRoute
  '/scenarios': typeof ScenariosRoute
  '/search': typeof SearchRoute
  '/shots': typeof ShotsRoute
  '/sound': typeof SoundRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/aspect': typeof AspectRoute
  '/bible': typeof BibleRoute
  '/budget': typeof BudgetRoute
  '/cards': typeof CardsRoute
  '/color': typeof ColorRoute
  '/composition': typeof CompositionRoute
  '/consistency': typeof ConsistencyRoute
  '/craft': typeof CraftRoute
  '/dna': typeof DnaRoute
  '/docs': typeof DocsRoute
  '/dop': typeof DopRoute
  '/editing': typeof EditingRoute
  '/glossary': typeof GlossaryRoute
  '/graduate': typeof GraduateRoute
  '/lab': typeof LabRoute
  '/learn': typeof LearnRoute
  '/lenses': typeof LensesRoute
  '/lighting': typeof LightingRoute
  '/movement': typeof MovementRoute
  '/pack': typeof PackRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/quiz': typeof QuizRoute
  '/recap': typeof RecapRoute
  '/scenarios': typeof ScenariosRoute
  '/search': typeof SearchRoute
  '/shots': typeof ShotsRoute
  '/sound': typeof SoundRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/aspect': typeof AspectRoute
  '/bible': typeof BibleRoute
  '/budget': typeof BudgetRoute
  '/cards': typeof CardsRoute
  '/color': typeof ColorRoute
  '/composition': typeof CompositionRoute
  '/consistency': typeof ConsistencyRoute
  '/craft': typeof CraftRoute
  '/dna': typeof DnaRoute
  '/docs': typeof DocsRoute
  '/dop': typeof DopRoute
  '/editing': typeof EditingRoute
  '/glossary': typeof GlossaryRoute
  '/graduate': typeof GraduateRoute
  '/lab': typeof LabRoute
  '/learn': typeof LearnRoute
  '/lenses': typeof LensesRoute
  '/lighting': typeof LightingRoute
  '/movement': typeof MovementRoute
  '/pack': typeof PackRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/quiz': typeof QuizRoute
  '/recap': typeof RecapRoute
  '/scenarios': typeof ScenariosRoute
  '/search': typeof SearchRoute
  '/shots': typeof ShotsRoute
  '/sound': typeof SoundRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/aspect'
    | '/bible'
    | '/budget'
    | '/cards'
    | '/color'
    | '/composition'
    | '/consistency'
    | '/craft'
    | '/dna'
    | '/docs'
    | '/dop'
    | '/editing'
    | '/glossary'
    | '/graduate'
    | '/lab'
    | '/learn'
    | '/lenses'
    | '/lighting'
    | '/movement'
    | '/pack'
    | '/pipeline'
    | '/pricing'
    | '/quiz'
    | '/recap'
    | '/scenarios'
    | '/search'
    | '/shots'
    | '/sound'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/aspect'
    | '/bible'
    | '/budget'
    | '/cards'
    | '/color'
    | '/composition'
    | '/consistency'
    | '/craft'
    | '/dna'
    | '/docs'
    | '/dop'
    | '/editing'
    | '/glossary'
    | '/graduate'
    | '/lab'
    | '/learn'
    | '/lenses'
    | '/lighting'
    | '/movement'
    | '/pack'
    | '/pipeline'
    | '/pricing'
    | '/quiz'
    | '/recap'
    | '/scenarios'
    | '/search'
    | '/shots'
    | '/sound'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/aspect'
    | '/bible'
    | '/budget'
    | '/cards'
    | '/color'
    | '/composition'
    | '/consistency'
    | '/craft'
    | '/dna'
    | '/docs'
    | '/dop'
    | '/editing'
    | '/glossary'
    | '/graduate'
    | '/lab'
    | '/learn'
    | '/lenses'
    | '/lighting'
    | '/movement'
    | '/pack'
    | '/pipeline'
    | '/pricing'
    | '/quiz'
    | '/recap'
    | '/scenarios'
    | '/search'
    | '/shots'
    | '/sound'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AspectRoute: typeof AspectRoute
  BibleRoute: typeof BibleRoute
  BudgetRoute: typeof BudgetRoute
  CardsRoute: typeof CardsRoute
  ColorRoute: typeof ColorRoute
  CompositionRoute: typeof CompositionRoute
  ConsistencyRoute: typeof ConsistencyRoute
  CraftRoute: typeof CraftRoute
  DnaRoute: typeof DnaRoute
  DocsRoute: typeof DocsRoute
  DopRoute: typeof DopRoute
  EditingRoute: typeof EditingRoute
  GlossaryRoute: typeof GlossaryRoute
  GraduateRoute: typeof GraduateRoute
  LabRoute: typeof LabRoute
  LearnRoute: typeof LearnRoute
  LensesRoute: typeof LensesRoute
  LightingRoute: typeof LightingRoute
  MovementRoute: typeof MovementRoute
  PackRoute: typeof PackRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  QuizRoute: typeof QuizRoute
  RecapRoute: typeof RecapRoute
  ScenariosRoute: typeof ScenariosRoute
  SearchRoute: typeof SearchRoute
  ShotsRoute: typeof ShotsRoute
  SoundRoute: typeof SoundRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspect': {
      id: '/aspect'
      path: '/aspect'
      fullPath: '/aspect'
      preLoaderRoute: typeof AspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composition': {
      id: '/composition'
      path: '/composition'
      fullPath: '/composition'
      preLoaderRoute: typeof CompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consistency': {
      id: '/consistency'
      path: '/consistency'
      fullPath: '/consistency'
      preLoaderRoute: typeof ConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dop': {
      id: '/dop'
      path: '/dop'
      fullPath: '/dop'
      preLoaderRoute: typeof DopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduate': {
      id: '/graduate'
      path: '/graduate'
      fullPath: '/graduate'
      preLoaderRoute: typeof GraduateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenses': {
      id: '/lenses'
      path: '/lenses'
      fullPath: '/lenses'
      preLoaderRoute: typeof LensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots': {
      id: '/shots'
      path: '/shots'
      fullPath: '/shots'
      preLoaderRoute: typeof ShotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound': {
      id: '/sound'
      path: '/sound'
      fullPath: '/sound'
      preLoaderRoute: typeof SoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AspectRoute: AspectRoute,
  BibleRoute: BibleRoute,
  BudgetRoute: BudgetRoute,
  CardsRoute: CardsRoute,
  ColorRoute: ColorRoute,
  CompositionRoute: CompositionRoute,
  ConsistencyRoute: ConsistencyRoute,
  CraftRoute: CraftRoute,
  DnaRoute: DnaRoute,
  DocsRoute: DocsRoute,
  DopRoute: DopRoute,
  EditingRoute: EditingRoute,
  GlossaryRoute: GlossaryRoute,
  GraduateRoute: GraduateRoute,
  LabRoute: LabRoute,
  LearnRoute: LearnRoute,
  LensesRoute: LensesRoute,
  LightingRoute: LightingRoute,
  MovementRoute: MovementRoute,
  PackRoute: PackRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  QuizRoute: QuizRoute,
  RecapRoute: RecapRoute,
  ScenariosRoute: ScenariosRoute,
  SearchRoute: SearchRoute,
  ShotsRoute: ShotsRoute,
  SoundRoute: SoundRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
